### ISSUE TITLE
Not picking up config file, provided via docker

### ISSUE THREAD

**Issue by rishiraaz** [idealista/prom2teams#100]
I converted the docker command to b e used as a helm deployment and mounted a volume with config.ini.
For some reason its not picking up the new file and still using the one at home/prom2teams/.

When i login to container and check i can see the config .ini at the correct location of opt/prom2teams

**Comment by jnogol** [comment]
Hi @rishiraaz,

I just spun up a container and can't see any `/home/prom2teams` folder. How are you setting the container?

**Comment by rishiraaz** [comment]
Hi @jnogol 
apologies, should have been more clear.
I am using a helm chart to spin up the container, I created the chart.

**Comment by rishiraaz** [comment]
@jnogol through helm chart I am mounting a volume at /opt/prom2teams and adding the config.ini to it.
When the container (pod) is up I login to and do a pwd which show the config.ini and prom2teams.sh( not sure about the name)  at the same location, I then check whether /opt/prom2teams is mounted or not, it is mounted and contains the config.ini.
So i check which config.ini is prom2teams using and see that its using the one which is the same directory as prom2teams.sh

**Comment by manuhortet** [comment]
Hey @rishiraaz,

> So i check which config.ini is prom2teams using and see that its using the one which is the same directory as prom2teams.sh

This is the expected behavior. I don't understand what the problem is. 
Can you tell us, exactly, what you want to happen that is not happening?
