### ISSUE TITLE
[Question]Is that possible to reload config without restarting prom2teams?

### ISSUE THREAD

**Issue by orangedeng** [idealista/prom2teams#104]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

We are trying to run `prom2teams` in kubernetes. I go through the code and it seems that restarting `prom2teams` is the only way to reload the configuration. It is not easy to add new teams/connectors. Like `alertmanager` and `prometheus`, they will reload the config file via API calls without restarting the app. If `prom2teams` have similar feature, it would be great help for using it in kubernetes.

**Comment by jnogol** [comment]
Working on it. Will release this soon :)

**Comment by jnogol** [comment]
Hi @orangedeng,

This is available in Prom2teams v2.4.0, just update your config and the service will take it.

Regards,
Jose
