### ISSUE TITLE
[Feature request] is there a helm chart available?

### ISSUE THREAD

**Issue by sosoriov** [idealista/prom2teams#109]
It would be great to have Helm/K8s support

**Comment by jperera** [comment]
Hi, @sosoriov! 

We don't plan to work on helm or another k8s integration soon. You have a Docker image available: [https://hub.docker.com/r/idealista/prom2teams](https://hub.docker.com/r/idealista/prom2teams)

If you decide to build your own helm chart, we are opened to contributions and we'd be glad to integrate your work.

Thanks for using Prom2teams and taking the time of providing us feedback :)

**Comment by miguel-chacon** [comment]
Take a look to latest release (2.5.0)

Thanks,
