### ISSUE TITLE
[Question] Use of custom alert labels in template

### ISSUE THREAD

**Issue by conradj87** [idealista/prom2teams#112]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

I am using prom2teams in Kubernetes, and would like to add additional metadata to the message in teams - things like namespace, pod, etc... All of these are values on the alert when viewed in prometheus or in alertmanager.

I've created and configured a template to use with prom2teams, but I'm not able to figure out how to use any "custom" labels on the alerts. Is this possible? Looking at [this line of code](https://github.com/idealista/prom2teams/blob/a35273cb597bd18f0bbd9c575f37f3d769388175/prom2teams/teams/alarm_mapper.py#L17) it appears that the template may be limited to some default labels/meta-data on the alert. Is there any way to access _all_ the labels on the alert? I couldn't find any examples of this, and couldn't get it working by trial and error.

[ Here's a screenshot](https://user-images.githubusercontent.com/3210990/57268267-25c77000-7051-11e9-91d6-9a23ac7e6bc9.png) of an example alert I'd like to leverage the labels on.

**Comment by jnogol** [comment]
Yep, just realized that there's no place in the code that take into account custom fields. We're gonna work on that. Hope we can release a fix for that next week or so.

**Comment by miguel-chacon** [comment]
@conradj87 Take a look to v2.3.1 for checking expectations fulfillment
