### ISSUE TITLE
Compatibility with Python 3.7

### ISSUE THREAD

**Issue by jnogol** [idealista/prom2teams#131]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Check if Prom2teams is already compatible with Python 3.7 and, if it doesn't, make it so.

**Comment by dortegau** [comment]
As Python 3.8 is the current stable version, should be checked with that version :)

**Comment by blalop** [comment]
Closing as this is already supported
