### ISSUE TITLE
Publish Helm chart

### ISSUE THREAD

**Issue by miguel-chacon** [idealista/prom2teams#143]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
Publish Helm chart package on Github Pages

### Steps to Reproduce

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 
### Versions
All

**Comment by Aaron-ML** [comment]
#136 Should be added
