### ISSUE TITLE
Prometheus "job" label not displaying in Teams

### ISSUE THREAD

**Issue by HenchmanNo21** [idealista/prom2teams#146]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

I am attempting to get the "job" label from the Prometheus alert to pass through to Teams, but it is not showing up. All other "extra_labels" in my alert are displaying as expected. I am simply using the v1 Swagger UI "Try it out" feature to send the test alerts, and I see that "job" is a label present in the example value for the payload.

### Steps to Reproduce

1. Load the Prom2Teams API v1 SwaggerUI page
2. Click "POST" / API
3. Click "Try it out"
4. Add custom JSON alert
5. Click Execute

**Expected behavior:** All "extra_labels" show up in Teams message as key / value

**Actual behavior:** All "extra_labels" EXCEPT "job" label show up in Teams

**Reproduces how often:** 100%
### Versions
2.5.0

### Additional Information
The following is the test JSON alert I am using:

{
  "status": "firing",
  "receiver": "app_perf_500_errors",
  "version": "4",
  "externalURL": "http://10.60.100.56:9093",
  "alerts": [
    {
      "status": "firing",
      "startsAt": "2019-09-11T18:07:05.325Z",
      "endsAt": "2019-09-11T18:08:05.325Z",
      "annotations": {
        "summary": "Response taking more than 10 seconds",
        "description": "Requests to /chris/test on test-service taking more than 10 seconds to resolve"
      },
      "labels": {
        "job": "test-service",
        "hostname": "CHRISTESTHOST001",
        "severity": "medium",
        "location": "Chris Test Location",
        "alertname": "AppResponseTimeGreaterThanThreshold",
        "method": "POST",
        "operator": "Operator",
        "path": "/chris/test",
        "status_code": "200"
      },
      "generatorURL": "10.60.100.56:9090"
    }
  ]
}

**Comment by miguel-chacon** [comment]
Hi @HenchmanNo21 ,

Try latest release (2.5.1)

**Comment by HenchmanNo21** [comment]
@miguel-chacon -- thank you so much! That's fixed it for me. The "job" label is now displaying along with the other "extra_labels".
