### ISSUE TITLE
Can't install prom2teams because werkzeug

### ISSUE THREAD

**Issue by frantsao** [idealista/prom2teams#162]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description
After werkzeug 1.0.0 release, prom2teams installing is broken.

### Steps to Reproduce

1. pip3 install prom2teams

**Expected behavior:** 
prom2teams installed without issues

**Actual behavior:** 
Logs like this:

```
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/local/lib/python3.7/dist-packages/werkzeug/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Reproduces how often:**
Always.
### Versions
All.

### Additional Information

Workaround: install werkzeug 0.16.1 then prom2teams

**Comment by miguel-chacon** [comment]
Already fixed
