### ISSUE TITLE
Add ability to silence alerts from Teams Alert cards

### ISSUE THREAD

**Issue by dortegau** [idealista/prom2teams#174]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Add the ability to silence alerts from alert templates. 

An action could be triggered from the template opening the Alertmanager UI to silence the current alert (that form could be pre filled using filters that could be passed as URL parameters):

```
http://[alertmanagerurl]/#/silences/new?filter=[FILTERS]
```

### Additional Information

https://github.com/prometheus/alertmanager/blob/master/ui/app/README.md

**Comment by pierrediancourt** [comment]
I've got an idea around this topic

If we can get the alertmanager uri in the jinja2 template we could then use it to generate api calls like 
```
curl https://alertmanager/api/v1/silences -d '{
      "matchers": [
        {
          "name": "alername1",
          "value": ".*",
          "isRegex": true
        }
      ],
      "startsAt": "2018-10-25T22:12:33.533330795Z",
      "endsAt": "2018-10-25T23:11:44.603Z",
      "createdBy": "api",
      "comment": "Silence",
      "status": {
        "state": "active"
      }
```
in the MessageCard 
like 
```
{
	"type": "ActionSet",
	"spacing": "small",
	"actions": [
		{
			"type": "Action.Http",
			"method": "POST",
			"body": "{{choiceinputid.value}}",
			"title": "OK",
			"url": "https://messagecardplaygroundfn.azurewebsites.net/api/HttpPost?code=zJaYHdG4dZdPK0GTymwYzpaCtcPAPec8fTvc2flJRvahwigYWg3p0A==&message=The card was moved to '{{choiceinputid.value}}' successfully"
		}
	]
}
```
found in https://messagecardplayground.azurewebsites.net/
