### ISSUE TITLE
Allow to configure multiple connectors

### ISSUE THREAD

**Issue by dortegau** [idealista/prom2teams#22]
To avoid creating multiple prom2teams instances, we should allow to configure multiple Microsoft Teams connectors on each prom2teams instance.

**Comment by ctolon22** [comment]
Any updates on this topic? I am interested in create different Connectors depending on the alert. 

Thank you

**Comment by dortegau** [comment]
Hi @ctolon22,

This feature will be available on 2018 1st quarter. Thanks for using prom2teams!

Regards,
Daniel

**Comment by dortegau** [comment]
Hi @ctolon22,

This feature is already in develop and will be soon released 👍 

Thank you!
