### ISSUE TITLE
Environment Variables in Helm chart

### ISSUE THREAD

**Issue by mebays** [idealista/prom2teams#229]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

There are a few things found:

When using the helm chart in version [3.1.0](https://github.com/idealista/prom2teams/tree/3.1.0/helm) the security context has been switched to a non root user. When the prom2teams_start.sh is triggered it tries to modify the fixed file path `/opt/prom2teams/config.ini` causing this error message in the logs. 

```bash
Traceback (most recent call last):
  File "/opt/prom2teams/replace_config.py", line 12, in <module>
    with open('/opt/prom2teams/config.ini', 'w') as file:
PermissionError: [Errno 13] Permission denied: '/opt/prom2teams/config.ini'
2020-10-29 17:20:36,821 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
2020-10-29 17:20:36,821 - werkzeug - INFO -  * Running on http://0.0.0.0:8089/ (Press CTRL+C to quit)
2020-10-29 17:20:36,824 - werkzeug - INFO -  * Restarting with stat
2020-10-29 17:20:41,713 - prom2teams_app - INFO - prom2teams started on 0.0.0.0:8089
```

This doesn't cause the system to crash, but is misleading on which config file is being used in the configuration. 

Looking further into the replace_config.py I noticed that is where the environment variables `PROM2TEAMS_PORT`, `PROM2TEAMS_HOST`, `PROM2TEAMS_CONNECTOR`, and `PROM2TEAMS_GROUP_ALERTS_BY` which are now being passed into the helm chart  gets used. These values try to modify `/opt/prom2teams/config.ini`, but the chart also passes `APP_CONFIG_FILE` setting it to `/opt/prom2teams/helmconfig/config.ini`, which I believed to be that actual config file. 

Which config file is actually being used in the helm chart?

If the APP_CONFIG_FILE is the actual config I would suggest removing the environments variables for the helm chart until the environment variables are more clearly implemented. 

### Steps to Reproduce

1. Deploy helm chart
2. Look at log messages

**Expected behavior:** No traceback to message to be seen

**Actual behavior:** Traceback Error message

### Versions

Version 3.1.0 primarily looking at the helm chart

**Comment by bansalrajat** [comment]
Any update on this?
