### ISSUE TITLE
[FEATURE] - Multiple fields for Group by

### ISSUE THREAD

**Issue by Hanoko** [idealista/prom2teams#238]
Hi,

It would be awesome if you could group the alerts by multiple Fields. Sometimes we have multiple alerts for multiple instances and multiple severity types. I would want to be able to receive, for example, all the critical alerts for one instance in one message and all the warnings in another one, so I can prioritize the critical ones and we know the difference between them

Thanks in advance.

**Comment by claas-fridtjof-lisowski** [comment]
@Hanoko Try this tool, that has the grouping options for templating, including a good example and good documentation:
[https://github.com/prometheus-msteams/prometheus-msteams/tree/master/examples](https://github.com/prometheus-msteams/prometheus-msteams/tree/master/examples)

**Comment by Hanoko** [comment]
I saw that tool, but is it better than prom2teams? I choosed prom2teams because it is on the offical prometheus page.

Thanks in advance.

**Comment by claas-fridtjof-lisowski** [comment]
I don't know whit the other tool isn't on the offical page but it's better from my point of view. Switched to it and all the templating is more how I was used to from the Alertmanager templating and I am very happy now with it.
Multiple connectors are available as well, it just doesn't have the Swagger UI to test payloads.
