### ISSUE TITLE
Selftest

### ISSUE THREAD

**Issue by rdoering** [idealista/prom2teams#255]
### Description

I would like to have to capability to set up an selftest, which will be scheduled periodically and calls the teams webhooks.

### Why is this needed?

I our case we do not get posts in teams. We are lucky about that but also asking our self, if prom2teams is still working.

**Comment by vicsufer** [comment]
Hi @rdoering thanks for the question.
If I understood correctly you want to check wheter prom2teams is healthy or not, we already have two endpoints for this functionality: `/alive` and `/ready`.

`/ready` returns 200 whenever prom2teams is ready to start working.
`/alive` returns 200 unless prom2teams has exited and obviously can't answer any request.

https://github.com/idealista/prom2teams/blob/29710102acb7748dc93cc1e827d2f5b8aa506206/prom2teams/app/api.py#L21-L27

**Comment by rdoering** [comment]
@vicsufer Many thanks for your fast answer. 

I meant a capability to send periodically a self-test message to the teams-channel to enable all channel-members 
to see, that this teams-channel is provided with alerts from prometheus even if no alert is active.

**Comment by blalop** [comment]
Hi @rdoering!

So, if I have understood correctly: you want to manually trigger prom2teams to send a message? We are doing something like that in [our e2e tests](https://github.com/idealista/prom2teams/blob/develop/tests/e2e/test.sh#L117), might this cover your use case? A cronjob with curl may be configured to run it periodically.

**Comment by rdoering** [comment]
I tought more about that prom2team gets triggered by it own but yes this should do the job, too. Thanks very much.

I played and read about the new endpoints /alive and /ready but I cant figure out how prometheus, because it is not part of the metrics.

**Comment by blalop** [comment]
If you want to get Prometheus metrics from prom2teams, there is a /metrics endpoint that can be enabled running prom2teams with the flag ```--enablemetrics```, documentation about that can be found in the readme. Feel free to open a support request issue if having troubles with that feature and we'll try to help you.

Closing this issue, as the main subject seems to be already solved. Thank you very much! :)
