### ISSUE TITLE
[SUPPORT] Mentioning individual person using "@"

### ISSUE THREAD

**Issue by bartwitkowski** [idealista/prom2teams#282]
### Description

Hey, we are using prom2teams in multiple projects and it works great!
Even if we can direct alerts to specific channel we also need to mention (ping) individual person inside those alerts. Just like using "@" with manual text that you can type in teams.
Is it possible? If yes, how can we achieve this? Adding simple "@xyz" into the alert description does not work :(.

**Comment by xafer337** [comment]
Is it not going to be implemented? I think this is a nice feature.
I would use it if it is added.

**Comment by frantsao** [comment]
At this time we didn't have found a solution for this issue, but we will try again.

**Comment by Hanoko** [comment]
Hi, 

This is a nice feature to have. Could you look at it if this is possible to implement?

Thanks for your work.
