### ISSUE TITLE
[FEATURE] include more alert properties

### ISSUE THREAD

**Issue by psi-4ward** [idealista/prom2teams#303]
Would be nice to include `externalURL`, `generatorURL`, `startsAt` and `endsAt` from the alertmanager [POST-Body](https://prometheus.io/docs/alerting/latest/configuration/#webhook_config) that we can include it in the template.

**Comment by psi-4ward** [comment]
😔

**Comment by martinsdyrby** [comment]
I would love this feature to be implemented :)

**Comment by IgorStadnyk** [comment]
**generatorURL and externalURL Missing in Teams Alerts via Alertmanager**

I'm using Alertmanager to send alerts to Microsoft Teams through the prom2teams integration, but I'm not seeing generatorURL and externalURL in the Teams messages. I've checked my Alertmanager configuration and the custom teams.j2 template, but I can't figure out why these URLs aren't being included.

Here’s an example of how I’ve modified the teams.j2 template:
"{%- set
  theme_colors = {
    'resolved' : '2DC72D',
    'critical' : '8C1A1A',
    'severe' : '8C1A1A',
    'warning' : 'FF9A0B',
    'unknown' : 'CCCCCC'
  }
-%}

{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "{% if status=='resolved' %} {{ theme_colors.resolved }} {% else %} {{ theme_colors[msg_text.severity] }} {% endif %}",
    "summary": "{% if status=='resolved' %}(Resolved) {% endif %}{{ msg_text.summary }}",
    "title": "Prometheus alert {% if status=='resolved' %}(Resolved) {% elif status=='unknown' %} (status unknown) {% endif %}",
    "sections": [{
        "activityTitle": "{{ msg_text.summary }}",
        "facts": [{% if msg_text.name %}{
            "name": "Alert",
            "value": "{{ msg_text.name }}"
        },{% endif %}{% if msg_text.instance %}{
            "name": "In host",
            "value": "{{ msg_text.instance }}"
        },{% endif %}{% if msg_text.severity %}{
            "name": "Severity",
            "value": "{{ msg_text.severity }}"
        },{% endif %}{% if msg_text.description %}{
            "name": "Description",
            "value": "{{ msg_text.description }}"
        },{% endif %}{
            "name": "Status",
            "value": "{{ msg_text.status }}"
        }{% if msg_text.extra_labels %}{% for key in msg_text.extra_labels %},{
            "name": "{{ key }}",
            "value": "{{ msg_text.extra_labels[key] }}"
        }{% endfor %}{% endif %}
        {% if msg_text.extra_annotations %}{% for key in msg_text.extra_annotations %},{
            "name": "{{ key }}",
            "value": "{{ msg_text.extra_annotations[key] }}"
        }{% endfor %}{% endif %}
        {% if msg_text.generatorURL %},{
            "name": "Generator URL",
            "value": "{{ msg_text.generatorURL }}"
        }{% endif %}
        {% if msg_text.externalURL %},{
            "name": "External URL",
            "value": "{{ msg_text.externalURL }}"
        }{% endif %}],
          "markdown": true
    }]
}
"
Despite these configurations, the URLs aren’t appearing in the Teams messages.

Questions:

1.Has anyone experienced this issue and found a way to include the generatorURL and externalURL in the alerts?
2.Are there any recent updates or plans to address this, as I've seen similar requests in other issues?
Thanks in advance for any help!

**Comment by viktor-roza** [comment]
Is it possible to reopen this topic and implent feature for externalURL, generatorURL. Thank you
