### ISSUE TITLE
[BUG] PROM2TEAMS_PROMETHEUS_METRICS

### ISSUE THREAD

**Issue by ebini** [idealista/prom2teams#325]
### Description

setting the Environment Variable PROM2TEAMS_PROMETHEUS_METRICS=true (like in the README.md
is not working (anymore)

### Steps to Reproduce

set PROM2TEAMS_PROMETHEUS_METRICS=true
connecting to /metrics returns still 404
```curl http://prom2teams:8089/metrics
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
````
**Expected behavior:**
metrics data

**Actual behavior:**
404

**Reproduces how often:** 
always

### Environment

deployed in k8s cluster
verified setting by "shelling" into the container
```
/opt/prom2teams $ printenv | grep PROM2TEAMS_PROMETHEUS_METRICS
PROM2TEAMS_PROMETHEUS_METRICS=true
```
### Additional Information

worked in older versions (but this was long time ago)

**Comment by santi-eidu** [comment]
Metrics are in port 9090, are you checking this port? I cannot reproduce the error.

**Comment by mateuszdrab** [comment]
Is there a way to revert to the old behavior?
The helm chart does not have a port for metrics and I'm running with Rancher's fork of prom2teams included in rancher-alerting-drivers so even if resolved here, it will take long time to get pulled into their repo.

https://github.com/idealista/prom2teams/blob/340d47d30d4263d7a5608206c5e884553c2dc0e2/prom2teams/app/configuration.py#L133
I think setting the ENV config parameter would revert the old behavior, but I'm not sure how to achieve that.
