### ISSUE TITLE
[Feature request] Dockerfile for running prom2teams with docker

### ISSUE THREAD

**Issue by ath88** [idealista/prom2teams#38]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

It would be awesome to be able to run this in a docker container, only having to inject a config file. Could this be of interest?

**Comment by jnogol** [comment]
Sure thing. I'm going to create a new branch called `features/dockerfile` and, when my colleagues review them, we'll merge it into master. Meanwhile, checkout to that branch and you'll be able to use it.

Thanks for your suggestion and for using Prom2teams.

Regards,
Jose
