### ISSUE TITLE
docker image built from supplied Dockerfile "server 500"

### ISSUE THREAD

**Issue by Justin-DynamicD** [idealista/prom2teams#42]
### Description

Created a container using the provided Dockerfile then used curl to send it a test alert.  Server logs an error message rather than sending:

### Steps to Reproduce

1. build the image ```docker build .```
2. run the image ```docker run -d -p 8089:8089 <imagename>```
3. curl some dummy data to test
```
curl -H "Content-type: application/json" -X POST   -d '{"receiver": "prom2teams", "status": "firing", "alerts": [{"status": "firing", "labels": {"alertname": "TestAlert", "key": "value"} }], "groupLabels": {"alertname": "TestAlert"}}'   http://<appropriateip>:8089
```

**Expected behavior:** [What you expect to happen]
an alert to be generated to teams

**Actual behavior:** [What actually happens]
curl returns:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 500</p>
        <p>Message: Error processing request.</p>
        <p>Error code explanation: 500 - Server got itself in trouble.</p>
    </body>
</html>
```

**Reproduces how often:** 100%

### Versions
tested in latest

**Comment by jnogol** [comment]
I'll take a look, thanks for your feedback

**Comment by jnogol** [comment]
Ok, just found what's happening. Prom2teams expects the alarm to have annotations in it (such as description and summary, based on https://prometheus.io/docs/prometheus/latest/configuration/template_examples/#simple-alert-field-templates). You can fork our repo or download our tests folder and doing

```
curl -H "Content-type: application/json" -d @tests/data/jsons/all_ok.json  <appropiated_ip>:8089
```

and see it is working.

Anyway, we just found that v1.3.0 was not released to PyPi, we're working on that.

**Comment by Justin-DynamicD** [comment]
thank you very much for the info.  Ill run some additional tests and validate things look OK.  Again:  very much appreciated.

**Comment by Justin-DynamicD** [comment]
Thank you,  I was able to successfully test/deploy prom2teams :)

**Comment by jnogol** [comment]
Glad to read that. Thanks for using Prom2teams!
