### ISSUE TITLE
Provide generatorURL to the template

### ISSUE THREAD

**Issue by tonnymadsen** [idealista/prom2teams#47]
It would be very nice to have the generatorURL as a fact in the Teams message as this would make it very easy to get to the raw data from the message.

**Comment by jnogol** [comment]
Hi @tonnymadsen,

Thanks for using Prom2teams and for your feedback. We'll add this suggestion to our backlog. If you feel like collaborating, feel free to open us a PR, any helpful hand is very appreciated.

Regards,
Jose
