### ISSUE TITLE
Question <Connector1> in Configuring Prometheus

### ISSUE THREAD

**Issue by Alexvianet** [idealista/prom2teams#62]
can U provide some example of this url:
in prom2teams i have:
Host: localhost
Port: 8089
Connector: <webhook url>
https://outlook.office.com/webhook/XXXXXXXXXXXXX@XXXXXXXXX/IncomingWebhook/XXXXXXXX

So in Prometheus Configuration i have to add:
url: 0.0.0.0:8089/v2/https://outlook.office.com/webhook/XXXXXXXXXXXXX@XXXXXXXXX/IncomingWebhook/XXXXXXXX

or 
0.0.0.0:8089/v2/webhook/XXXXXXXXXXXXX@XXXXXXXXX/IncomingWebhook/XXXXXXXX

**Comment by Gkrlo** [comment]
Hi @Alexvianet :)
'Connector' is the connector's name you have. So the endpoint to send the HTTP POST requests is:
'0.0.0.0:8089/v2/Connector'. 
Just for letting you know also, using the '/v2' allows you to change 'Connector' for something more specific (e.g 'Team1' , sending to '0.0.0.0:8089/v2/Team1')
Hope this helps. If you need more help don't hesitate to ask us. 
Regards.

**Comment by Alexvianet** [comment]
thanks i got it

**Comment by Alexvianet** [comment]
2018-04-10 10:55:37,832 - werkzeug - INFO - 10.233.170.15 - - [10/Apr/2018 10:55:37] "POST /v2/Connector HTTP/1.1" 404 -

[Microsoft Teams]                                   
# At least one connector is required here           
Connector: "https://outlook.office.com/webhook/XXXXXXXXXXXXX@XXXXXXXXX/IncomingWebhook/XXXXXXXX
# AnotherConnector: <webhook url>   
# ...
#
[HTTP Server]
Host: 0.0.0.0

**Comment by jnogol** [comment]
Hi @Alexvianet,

We're working on this issue, that is related to #61. Stay tuned :)

**Comment by Alexvianet** [comment]
Hi yep it fix errors in log but i have not still received anything to teams

**Comment by jnogol** [comment]
Hmmm... Just tried again and works perfectly for me. How are you setting up Prom2teams? Did you update your Prom2teams version?

Here's my testing `docker-compose.yml`, in case you're using Docker:

```yaml
version: '3'
services:
 prom2teams:
   image: idealista/prom2teams
   hostname: prom2teams
   ports:
   - "8089:8089"
   environment:
     - PROM2TEAMS_CONNECTOR=myconnectorurlwithoutquotes
```

And then:
```bash
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"status":"Resolved","alerts":[{"annotations":{"summary":"Disk usage alert on CS30.evilcorp","description":"disk usage 93% on rootfs device"},"endsAt":"2017-05-09T07:01:37.803Z","generatorURL":"my.prometheusserver.url","startsAt":"2017-05-09T07:01:37.803Z","status":"Resolved","labels":{"fstype":"rootfs","mounterpoint":"/","instance":"cs30.evilcorp","device":"rootfs","job":"fsociety","alertname":"DiskSpace","severity":"severe"}}],"receiver":"test_webhook","externalURL":"my.prometheusalertmanager.url","version":"4"}' 'http://localhost:8089/v2/Connector'
```

and got:
![imagen](https://user-images.githubusercontent.com/15360402/38615499-2d33aa82-3d91-11e8-8833-f14bf9b206ab.png)

**Comment by Alexvianet** [comment]
I use it in prometheus VM i have unzip 2.0.3.zip and run prom2teams with 
```
#!/bin/bash

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

RUN_DIR=/var/vcap/sys/run/prom2teams
LOG_DIR=/var/vcap/sys/log/prom2teams
mkdir -p ${RUN_DIR} ${LOG_DIR}

PIDFILE=${RUN_DIR}/prom2teams.pid

source /var/vcap/packages/prom2teams/common/utils.sh
exec 1>> ${LOG_DIR}/$(basename "$0").stdout.log
exec 2>> ${LOG_DIR}/$(basename "$0").stderr.log

export PATH=/var/vcap/packages/prom2teams/prom2teams/bin:${PATH}

case $1 in
  start)
    pid_guard ${PIDFILE} "prom2teams"
    echo $$ > ${PIDFILE}

    ulimit -n 65536

    exec prom2teams --configpath /var/vcap/jobs/prom2teams/config/prom2teams-config.ini \
      >>  ${LOG_DIR}/prom2teams.stdout.log \
      2>> ${LOG_DIR}/prom2teams.stderr.log
    ;;

  stop)
    kill_and_wait ${PIDFILE}
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1
  ;;

esac
exit 0

```
and my config/prom2teams-config.ini
![Uploading Screenshot from 2018-04-11 15-36-03.png…]()

**Comment by Alexvianet** [comment]
when i run Tour Curl, I got:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Comment by Alexvianet** [comment]
I am on 99% sure that i fuckuped some where)

**Comment by jnogol** [comment]
Try removing the quotes from the connector and restart Prom2teams. Plus, it looks like that your webhook url is incomplete. I don't know if that was on purpose (if so, well done :) )

**Comment by Alexvianet** [comment]
i have cut it to insecure stuff =)

**Comment by Alexvianet** [comment]
same issue -=(
2018-04-11 13:11:14,180 - werkzeug - INFO - 10.233.168.2 - - [11/Apr/2018 13:11:14] "POST /v2/Connector HTTP/1.1" 404 -

**Comment by Alexvianet** [comment]
receivers:
[{"name":"slack-receiver","webhook_configs":[{"send_resolved":true,"url":"
http://localhost:8089/v2/Connector"}]}]
This is my alertmanager config
There is webhook_configs type

**Comment by jnogol** [comment]
Ooops, sorry. Not enough caffeine in my system yet :laughing: 

So I read in a previous message that it is working now?

**Comment by Alexvianet** [comment]
can U send me your alertmanager template, ill be very grateful

**Comment by Alexvianet** [comment]
Finally works now thanks a lot

**Comment by jayraviteja** [comment]
> Finally works now thanks a lot

How it worked, could you pls confirm?

**Comment by Maleware** [comment]
Hey to this issue, I want to use prom2teams and my config.ini looks like this:
`[HTTP Server]
Host: 0.0.0.0
Port: 8089

[Microsoft Teams]
Connector: <My-Webhook>
[Group Alerts]
Field: 

[Log]
Level: DEBUG/opt/prom2teams`

My alertmanager bit looks like this:

`receivers:
    # 'null' is a workaround for a bug in alertmanager. Won't work without this additional receiver name.
    - name: 'null'
    - name: 'prometheus-msteams'
      webhook_configs:
        - url: 0.0.0.0:8089/v2/Connector
          send_resolved: true
      #- '/etc/alertmanager/config/*.tmpl'
    route:
      receiver: 'prometheus-msteams'
      group_by: [alertname]`

For this bit, I get a error with alertmanager, stating it cannot parse the url. That's fine I guess.

Changing to: `- url: http://0.0.0.0:8089/v2/Connector` gives me a connection refused. Using https:// gives me the exact same error. 

Can somebody help me?
