### ISSUE TITLE
pip3 install prom2teams error      ImportError: No module named req. New pip version  10 changed api

### ISSUE THREAD

**Issue by Alexvianet** [idealista/prom2teams#65]
for some reason now i am getting an error after:
pip3 install prom2teams 

$ sudo pip3 install prom2teams
Collecting prom2teams
  Downloading prom2teams-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2tkA24/prom2teams/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2tkA24/prom2teams/

**Comment by Gkrlo** [comment]
Hi @Alexvianet 
prom2teams does not support python 3.4. Try to install it with 3.5 or 3.6 please. :)
Regards.

**Comment by RonnyPfannschmidt** [comment]
@Gkrlo the pip usage is broken in any case and no longer working on pip 10

**Comment by Alexvianet** [comment]
the same issue, python is not a reason of fail, pip 10 no longer installed it.

**Comment by jnogol** [comment]
Hi @RonnyPfannschmidt, @Alexvianet, we've updated Prom2teams to v2.0.4 and hopefully fixed this issue. I'm closing it. If you ran into any problem, please reopen the issue.

Thanks to both for your feedback and using Prom2teams.
