### ISSUE TITLE
[Question] Multiple connectors

### ISSUE THREAD

**Issue by Abulfat** [idealista/prom2teams#81]
I have seen this already been addressed in https://github.com/idealista/prom2teams/issues/22
However I could not find any references on how to do this in docs. Could you please point me in right direction? Again, we need to be able to pass multiple connectors to Docker container via env variables.

**Comment by jnogol** [comment]
Hi @Abulfat,

Are you using Prom2teams' DockerHub image? If yes, this container doesn't support multiple connectors out of the box **yet**. As a workaround, you can provide a custom `config.ini` via Docker volume to the container and use env vars in your Dockerfile/Docker compose file.

Regards,
Jose

**Comment by Abulfat** [comment]
Hi @jnogol ,

Thanks for response and the tip. I'll do just that for now.

Kind Regards,
Abulfat
