### ISSUE TITLE
Allow Docker container to accept config file

### ISSUE THREAD

**Issue by conradj87** [idealista/prom2teams#97]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

I'm using prom2teams in a docker container, and finding the environment variable config approach to be a little difficult to use and limits the user to one connector. A typical pattern I've followed in the past with Prometheus, Alertmanager and several other utilities is to mount the config via a docker volume. 

I propose removing the existing environment variables and other docker-specific workflow items in favor of a more standard approach using docker volumes. This would have several advantages:

* Allow multiple connector definitions
* Consistent behavior and config patterns across all platforms

**Comment by jnogol** [comment]
Hi @conradj87,

Well, actually nothing stops you from using a volume for the configuration. In #81, we addressed this very way of having multiple connectors. We prefer leaving open a way to use our Docker image with no volumes and just environment variables.

What might be (is) true is that the readme doesn't suggest this way of using the prom2teams and could be a good idea.

And thanks for using Prom2teams and taking the time of providing us feedback :)

**Comment by conradj87** [comment]
Thanks @jnogol. It still seems a little counter-intuitive to me, but we can just create our own docker container to support what we're wanting.

**Comment by jnogol** [comment]
It looks intuitive to me, but of course because I made it haha. Could you please tell me why you think is counter-intuitive and how would you do it (PRs are more than welcome :D )?

**Comment by conradj87** [comment]
Sure. I just feel that having two ways of configuration, config.ini if you're using the binary, environment variables if you're using the container, is un-necessary. The pattern of using volumes for config files is a pretty common and well known pattern.

Looking at the comments in #81 I don't really understand how that would work. Even if I specify a custom `config.ini` and add additional variables, the `replace_config.py` file only does a find and replace on the pre-defined variables. How would additional variables work?

Now that I'm looking at it a little closer, I think as long as the config.ini is mounted at `/opt/prom2teams/config.ini` it should bypass the variable replacement altogether.
